### ISSUE TITLE
Special tokens in square brackets recognized as atoms?

### ISSUE THREAD

**Issue by hogru** [MolecularAI/pysmilesutils#3]
I stumbled upon your library (thank you for that) and want(ed) to use it for SMILES encoding with a Transformer model. I replaced the default of the special tokens with tokens that are somewhat "typical" in transformer land:

```
beginning_of_smiles_token: str = "[CLS]",  # SH: Changed from "^"
end_of_smiles_token: str = "[SEP]",  # SH: Changed from "&"
padding_token: str = "[PAD]",  # SH: Changed from " "
unknown_token: str = "[UNK]",  # SH: Changed from "?"
```

Encoding and Decoding SMILES with the `SMILESAtomTokenizer` returns the special tokens in the string, i.e. `[CLS]<SMILES>[SEP]`, so my guess is, that the parser recognizes the special tokens as atoms? I'm uncertain if you consider this to be a bug, intentional, … but at least, so you are aware.

**Comment by EBjerrum** [comment]
Oh, it depends on the tokenizer scheme employed. But yes, in SMILES syntax, things within square brackets is an atom with special extra info, e.g. hydrogen count, stereo or similar, so the default tokenizer scheme creates tokens out of everything in square brackets. In you case the special tokens. 

There may be some stripping of padding that may not work with your choice of tokens, but otherwise I think it should work. In SMILES LP we usually use ^&? and " ", they are not part of normal SMILES syntax, and you may recognize the anchors from regular expressions.

**Comment by hogru** [comment]
@EBjerrum, thank for the background info about the choice of the special tokens.
